---
services:
  legacy-mongo:
    build:
      context: ./build/deps
      dockerfile: mongo.Dockerfile
    container_name: legacy-mongo
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: legacy-mongo
