---
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password

  maxscale:
    image: mariadb/maxscale:23.08.4
    restart: on-failure
    container_name: maxscale
    ports:
      - 27017:27017
    volumes:
      - ./config/maxscale.cnf:/etc/maxscale.cnf

networks:
  default:
    name: mariadb
