---
services:
  mongo:
    image: mongodb/mongodb-community-server:5.0.26-ubuntu2004
    container_name: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

networks:
  default:
    name: mongo
